#!/usr/bin/env python3

from selenium import webdriver

#open browser and go to page
browser = webdriver.Chrome('/usr/local/bin/chromedriver') #need to download chromedriver and place in correct directory
browser.get('https://dashboard.zopim.com/#visitors/visitor_list/state') #load page on new browser window. May need to login

#get login info
user = browser.find_element_by_css_selector('#login_form > input:nth-child(1)')
password = browser.find_element_by_css_selector('#login_form > input:nth-child(2)')
loginClick = browser.find_element_by_css_selector('#sign_in > button')

#log into chat
user.send_keys('username')
password.send_keys('password')
loginClick.click()

#wait for page to load before seacrhing for button
browser.implicitly_wait(5)

#begin monitoring
button = browser.find_element_by_class_name('react_meshim_dashboard_components_navBar_OldServeButton')

while True:
    if button.text == 'Serve 1 Request':
        button.click()
        continue
    else:
        continue
